name: 'Convert HTML to Markdown'
description: 'Action converting HTML to Markdown using turndown library'
inputs:
  html-file:
    description: 'HTML file to convert'
    required: true
outputs:
  markdown-content:
    description: 'Markdown output'
  markdown-file:
    description: 'Markdown file (located into the same folder as the input file)'
runs:
  using: 'node20'
  main: 'dist/index.js'
